### ISSUE TITLE
成功登录后闪退

### ISSUE THREAD

**Issue by SuperTian007** [Leaking/WeGit#2]
报错：
```
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
            at com.google.gson.Gson.fromJson(Gson.java:822)
            at com.google.gson.Gson.fromJson(Gson.java:775)
            at com.google.gson.Gson.fromJson(Gson.java:724)
            at com.quinn.httpknife.github.GithubImpl.receivedEvent(GithubImpl.java:277)
            at com.quinn.githubknife.interactor.FindItemsInteractorImpl$8.run(FindItemsInteractorImpl.java:287)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by Leaking** [comment]
OK,这个情况之前也遇到过，我尽快解决！谢谢

**Comment by cooliean** [comment]
这个问题，我在屏蔽某些代码后进入应用，登录后还是看到过，好像是api 路径不对，返回的结果不对

**Comment by Leaking** [comment]
这个问题是由于不支持邮箱登陆造成的，如果使用账号登陆即可，现在修复这个bug了，邮箱登陆在最新的代码中支持了，我现在关闭这个issue，谢谢 @SuperTian007  @cooliean
