### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by cooliean** [Leaking/WeGit#4]
java.lang.IllegalArgumentException: no such account
            at android.os.Parcel.readException(Parcel.java:1435)
            at android.os.Parcel.readException(Parcel.java:1385)
            at android.accounts.IAccountManager$Stub$Proxy.getAuthToken(IAccountManager.java:929)
            at android.accounts.AccountManager$5.doWork(AccountManager.java:923)
            at android.accounts.AccountManager$AmsTask.start(AccountManager.java:1472)
            at android.accounts.AccountManager.getAuthToken(AccountManager.java:921)
            at com.quinn.githubknife.account.GitHubAccount.getAuthToken(GitHubAccount.java:80)
            at com.quinn.githubknife.interactor.UserInfoInteractorImpl$2.run(UserInfoInteractorImpl.java:73)
            at java.lang.Thread.run(Thread.java:841)

**Comment by Leaking** [comment]
In some devices,the AccountManager API does not work properly.
